parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mainick\KeycloakClientBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Token/KeycloakResourceOwner.php,EventSubscriber/TokenAuthListener.php}'

    Mainick\KeycloakClientBundle\Interface\IamClientInterface:
        public: true
        alias: Mainick\KeycloakClientBundle\Provider\KeycloakClient

    Mainick\KeycloakClientBundle\Provider\KeycloakClient:
        bind:
            bool $verify_ssl: '%mainick_keycloak_client.keycloak.verify_ssl%'
            string $base_url: '%mainick_keycloak_client.keycloak.base_url%'
            string $realm: '%mainick_keycloak_client.keycloak.realm%'
            string $client_id: '%mainick_keycloak_client.keycloak.client_id%'
            string $client_secret: '%mainick_keycloak_client.keycloak.client_secret%'
            string $redirect_uri: '%mainick_keycloak_client.keycloak.redirect_uri%'
            string $encryption_algorithm: '%mainick_keycloak_client.keycloak.encryption_algorithm%'
            string $encryption_key: '%mainick_keycloak_client.keycloak.encryption_key%'
            string $encryption_key_path: '%mainick_keycloak_client.keycloak.encryption_key_path%'
            string $version: '%mainick_keycloak_client.keycloak.version%'

    Mainick\KeycloakClientBundle\Provider\KeycloakAdminClient:
        bind:
            bool $verify_ssl: '%mainick_keycloak_client.keycloak.verify_ssl%'
            string $base_url: '%mainick_keycloak_client.keycloak.base_url%'
            string $admin_realm: '%mainick_keycloak_client.admin_cli.realm%'
            string $admin_client_id: '%mainick_keycloak_client.admin_cli.client_id%'
            string $admin_username: '%mainick_keycloak_client.admin_cli.username%'
            string $admin_password: '%mainick_keycloak_client.admin_cli.password%'
            string $version: '%mainick_keycloak_client.keycloak.version%'

    Mainick\KeycloakClientBundle\Controller\KeycloakController:
        public: true
        bind:
            $defaultTargetRouteName: '%mainick_keycloak_client.security.default_target_route_name%'
        tags: [ 'controller.service_arguments' ]

    Mainick\KeycloakClientBundle\Security\User\KeycloakUserProvider:
        public: true
#        tags:
#            - { name: mainick_keycloak_security.user_provider, alias: oauth }

    Mainick\KeycloakClientBundle\EventSubscriber\ExceptionListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Mainick\KeycloakClientBundle\EventSubscriber\LogoutAuthListener:
        public: true
        arguments:
            $defaultTargetRouteName: '%mainick_keycloak_client.security.default_target_route_name%'
        tags:
            - { name: kernel.event_listener, event: 'Symfony\Component\Security\Http\Event\LogoutEvent', priority: -10 }

    # Rimuovi questi normalizzatori dall'autowiring automatico per evitare
    # che Symfony provi a iniettare dipendenze circolari
    Mainick\KeycloakClientBundle\Serializer\CollectionDenormalizer:
        autowire: false
        autoconfigure: false
        public: false
        # Non aggiungere tag

    Mainick\KeycloakClientBundle\Serializer\AttributeNormalizer:
        autowire: false
        autoconfigure: false
        public: false
        # Non aggiungere tag

    Mainick\KeycloakClientBundle\Serializer\RepresentationDenormalizer:
        autowire: false
        autoconfigure: false
        public: false


#    Mainick\KeycloakClientBundle\Security\EntryPoint\KeycloakAuthenticationEntryPoint: ~
#    Mainick\KeycloakClientBundle\Security\Authenticator\KeycloakAuthenticator: ~
